=== aryaniken/Q1W2E32C/brnghd.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="baranghardware">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="barang"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="barang">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="kode"/>
                <xs:element ref="deskripsi"/>
                <xs:element ref="harga"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="kode">
    	<xs:simpleType>
    		<xs:restriction base="xs:string">
    			<xs:pattern value="[A-Z][A-Z]-[0-9][0-9][0-9][0-9]-[A-Z][A-Z]"></xs:pattern>
    		</xs:restriction>
    	</xs:simpleType>
    </xs:element>
    <xs:element name="deskripsi" type="xs:string"/>
    <xs:element name="harga">
    	<xs:simpleType>
    		<xs:restriction base="xs:decimal">
    			<xs:pattern value=".+"></xs:pattern>

    			<xs:minInclusive value="1999.999"></xs:minInclusive>
    		</xs:restriction>
    	</xs:simpleType>
    </xs:element>
</xs:schema>

=== aryaniken/Q1W2E32C/brnghd.xml
<?xml version="1.0" encoding="UTF-8"?>
<baranghardware xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="brnghd.xsd">
	
<barang>

<kode>AY-4565-SW</kode>

<deskripsi>APP Windows 10</deskripsi>

<harga>5000.000</harga>

</barang>


<barang>

<kode>TU-1934-JG</kode>

<deskripsi>Windows 8 full</deskripsi>

<harga>5000</harga>

</barang>


<barang>

<kode>AG-7899-GG</kode>

<deskripsi>Ms Excel full crack</deskripsi>

<harga>2200.000</harga>

</barang>

</baranghardware>
